app:
  name: "AQMS"
  version: "2.0.0"
quality_thresholds:
  critical_return_rate: 15
  warning_return_rate: 10
ai_models:
  default: "gpt-4o"
  fine_tuned: "ft:gpt-4o-2024-08-06:vive-health-quality-department:qms-v2-stable-lr:CM1nuhta"
export_formats:
  - docx
  - pdf
  - xlsx
